// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/25/2025, 12:27:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/workspaces/calcolo.online.nuxt.1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/calcolo.online.nuxt.1/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/calcolo.online.nuxt.1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/calcolo.online.nuxt.1/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/calcolo.online.nuxt.1/plugins/**/*.{js,ts,mjs}","/workspaces/calcolo.online.nuxt.1/composables/**/*.{js,ts,mjs}","/workspaces/calcolo.online.nuxt.1/utils/**/*.{js,ts,mjs}","/workspaces/calcolo.online.nuxt.1/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/calcolo.online.nuxt.1/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspaces/calcolo.online.nuxt.1/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspaces/calcolo.online.nuxt.1/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;